### ISSUE TITLE
proposed plugin for managing external feff runs

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#103]
Here's the plugin: https://gist.github.com/bruceravel/e1029c6f6a9b7c2554e3

I'd like to see it live in `plugins/xafs/`.

For feff85exafs unit testing as well as the general testing framework, I found that I needed a convenient way of running feff from larch.  To test this plugin, I have dropped the content of that gist in `/usr/local/share/larch/plugins/xafs` and run the unit tests and the general testing framework successfully.  I have also tested it from the larch command line.

The `run()` method manages:
 1. making the system call
 1. writing a useful log file
 1. writing screen messages about feff's progress
 1. managing arbitrary input files names while taking care not to clobber an existing `feff.inp`

It can run feff85exafs monolithically or as individual modules.  It has a mechanism for using either the installed executables or newly compiled ones from the local git repository (i.e. general testing vs. unit testing).  It can also run old versions of feff provided the name of the executable begins with "feff", e.g. `feff6`.

Obviously, this will eventually become obsolete as the feffpath library matures, but for now it is rather helpful to me.

**Comment by newville** [comment]
@bruceravel   that looks fantastic.  A couple small suggestions:

1. Is 'monofeff' the right name?  Perhaps 'feffrunner' or some other name that indicates it is a thing that will run feff.    Not sure .....

2.  If '_larch' is passed in, it's not necessary to create a new Interpreter instance.

3. The location of the feff executable could be stored and read from a value in the larch symbol table, so that one might do something like (again, a suggestion... modifications welcome):

```python
  larch>  _xafs.feff_executable = '/usr/local/bin/feff8'
  larch>  feff_runner = monofeff(feffinp='path/to/feff.inp')
  larch>  feff_runner.run()

```
That way, the "find where the feff executable is could be something like

```python
    feff_exe = None
    if _larch is not None:
         feff_exe = getattr(_larch.symtable._xafs, 'feff_executable', None)
    if feff_exe is None:
        # <handle unspecified feff exe, either complain or use some sensible default>
    else:
        # <use that feff_exe with subprocess.Popen()> 
```
And, of course, we could just have binary versions of feff6 and feff8exafs included in the distribution, in the bin folder under _sys.config.sys_larchdir.

Anyway, a pull request for this to be included in plugins/xafs would be great!

**Comment by bruceravel** [comment]
Done. See #108.
