### ISSUE TITLE
Typo in plugins/math/__init__.py

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#114]
Hi Matt,

I could do a PR, I suppose, but this is a tiny thing.

You misspelled "lorentzian" at

https://github.com/xraypy/xraylarch/blob/master/plugins/math/__init__.py#L5

resulting in
```
bruce@titanium [xraylarch](master) > larch
  Larch 0.9.24 (28-Oct-2014) M. Newville and the Larch Development Team
  using python 2.7.6, numpy 1.9.1, wx-enabled, wx version 2.8.12.1
Python Error in plugin '/home/bruce/.larch/plugins/xafs/deconvolve.py', line 0
   ^
ImportError: cannot import name lorentzian
Python Error in plugin '/home/bruce/.larch/plugins/math/smoothing.py', line 0
   ^
ImportError: cannot import name lorentzian
Python Error in plugin '/home/bruce/.larch/plugins/math/convolution1D.py', line 0
   ^
ImportError: cannot import name lorentzian
larch> 
```

**Comment by newville** [comment]
this should work on master now.   That is, master passes all tests for me as of now (f22ed6b14e26da74f0253b0cf9b7410ab27c5316).

I totally messed up master, thinking I was working on a branch.  Basically,  everything from e2e2ef695f656839401fca797087580b0614f9f8 on was *meant to be* on a separate branch (one of the pitfalls of using multiple computers, a DVCS, and using github master as "central", I suppose). 

The changes since e2e2ef69 really are experimental, and I'll probably change the current behavior.  I'm try to get to a point where

```python
import larch
from larch_plugins.xafs import autobk, mback, xftf
from larch_plugins,xray import material_mu 
```
(or similar syntaxl) and so on work for writing plugins, or using larch as a more normal python package, without the irritating `use_plugin_path()`.    It's requires a bit more magic and fussing around than I'd like.

Anyway, I'll be more sure about working on not-master, and merge only when it actually works.

**Comment by bruceravel** [comment]
I find this really helpful: https://github.com/jimeh/git-aware-prompt

**Comment by newville** [comment]
Fixed.
