### ISSUE TITLE
Qt backend via SILX toolkit?

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#152]
Hi,

Is there any interest in adding a Qt version of Larch (something the user could chose at the setup stage)? The ESRF is building a Qt-based toolkit, [SILX](https://github.com/silx-kit/silx), which could be used by Larch as plotting backend instead of wxmplot/wxutils.

I'm not deep enough in the library architecture to see if this "plot backend layer" is something that could be done easily. If there is interest/feasibility I could try to implement it.

Comments are welcome,
Mauro

**Comment by newville** [comment]
@maurov Thanks, and great to hear from you!   Hope you're doing well.

I have no objections to Qt-based GUIs for Larch.  All of the GUI backend stuff is cleanly separated from the processing code.  Of course, currently most of the exposed applications, including the command-line "larch" program are wx-programs.  But, it would not be hard to write a command-line program with a Qt event-loop that could then use Qt-based tools.   I don't plan to switch from wxPython to PyQt as the main or only GUI toolkit any time soon, but I'd be happy to (try to) help support PyQt or PySide with Larch.

For me, wxmplot is a key component.  Porting this to PyQt/PySide would probably not be hard (and might be a nice library anyway), and would go a long way to making a Qt backend for Larch.

Silx looks potentially interesting, but I have very serious reservations about it too.  I have never tried it, and know nothing about its plotting capabilities.    My reservation is related to its very deliberately choice to not use scipy or anything that depends on scipy.  That is actually a show-stopper for me, and I would caution anyone interested in slix about this fatal flaw.  A main reason for using Python for scientific work is the available libraries build in the "scipy stack",  scipy,  sckit-learn, scikit-image, pandas, matplotlib, etc.  We *want* to use these tools.  I would encourage anyone interested in using silx to complain loudly about this: it is deliberately ignoring vast quantities of work by others.  For example, It has hand-coded (in python, no less!) version of least-squares fitting instead of using scipy.optimize or lmfit.   This willful ignorance of the work of others makes it hard for me to take such a project seriously.  I'm trying to participate with the scikit-beam project, which has a much healthier approach to collaboration and understanding its place in the scientific python eco-system.  It is unfortunate that the silx developers have chosen to ignore such work.

Anyway, adding Qt tools to Larch would be fine with me.  Using Larch from Python in a Qt-based app is also fine.  I'd be happy to help anyway I can, but I'm afraid my PyQt skills are mediocre.

**Comment by maurov** [comment]
@newville thanks for your comments. I'm doing well... moving to new professional adventures that should permit me to come back to Larch and EXAFS analysis soon.

 I fully agree that the choice of not using Scipy in silx.fit is unfortunate, but apart for this module that can be easily substituted by scipy-based projects (as it is now in Larch), the [silx.gui.plot](https://pythonhosted.org/silx/modules/gui/plot/index.html) module has nice PyQt/PySide widgets based on Matplotlib. In my view, silx.gui.plot is to Qt wat wxmplot is to Wx.

I like the fact that the core of Larch library is still working even if Wx is not available. My idea would be to include some basic Qt tools to Larch (mainly a backend to the 'plot' command) in the case the user does not have Wx available or prefers working in a Qt environment (e.g. ipython with Qt). Having a full Qt-based GUI in Larch is beyond my scope and would make no sense to duplicate things.

It should be relatively easy to implement `larch.plugins.qt.plotter`. I can give it a try and then we see if it is worth to include or not.

**Comment by maurov** [comment]
@newville, after giving a try to implementing a Qt-based basic (=dirty) plotter plugin, I decided that this is NOT the way to go. It is much simpler and cleaner to have a separate Qt application using Larch as XAFS library.
