### ISSUE TITLE
[contributing guidelines] proposal for flake8 + black?

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#267]
@newville I would propose to recommend using [flake8](https://gitlab.com/pycqa/flake8) as linter and [black](https://black.readthedocs.io/en/stable/) as code formatter. The advantage of `flake8` over other linters is that it is a wrapper on top of the others, gluing together these tools. `black` will ensure having a clean code formatted the same way, independently who codes it. Both tools can be seamlessly integrated in modern Python IDEs (e.g. Visual Studio Code).

If this proposal is accepted, I would add this in a `CONTRIBUTING` file with some guidelines and enforce those two tools in future developments. Existing files could be ported to this style progressively.

**Comment by maurov** [comment]
And for documentation we could use as linter [rstcheck](https://github.com/myint/rstcheck).

**Comment by newville** [comment]
@maurov   I am not a fan of Black, at all.
  
Flake8 is not too bad.  But  PEP8 is a guide, it is not meant to be blindly followed or enforced.   It is a fine thing to keep in mind when writing code.  For sure, enforcing a line length of 79 characters leads to problems.  Sometimes code is improved with more than one space on either side of an equals sign.  And so on. 

Using Flake8 as a report of PEP8 compliance is fine.  Using it as a way to start a code review is OK.  But saying "this code passes all the tests but fails because of PEP8"  raises the barrier for contributing.  I would rather try to lower that barrier, even if it means having to clean up code after merging for something like removing trailing whitespace. 

Rstcheck is at least doing some validity checking, so is not only about style.

We use import hooks with flake8 and rstcheck in `lmfit`.  I can live with those.  I am sure that large swaths of Larch would trigger some flake8 warnings.   I would suggest we address those one at a time,  and not prevent changes from being imported because parts of a file violate PEP8 and not encourage PEP8-ifying code just for the sake of PEP8.

**Comment by maurov** [comment]
@newville thanks for your comments. OK, it is fine for me to live without Black formatting existing code in Larch and use Flake8 only as a helper for PEP8 compliance.
