### ISSUE TITLE
wxpython dependency

### ISSUE THREAD

**Issue by mrakitin** [xraypy/xraylarch#280]
Hello @newville! I have a question. Are there any plans for making the `wxpython` dependency optional? I have a concern that this hard dependency is not catching up with the latest Python versions in the `defaults` conda channel: https://anaconda.org/anaconda/wxpython/files. The highest Python version it's built for is Python 3.7 there. In the `conda-forge` channel the situation is a bit better, 3.8 is supported, but currently 3.9 is GA, but wxpython is not packaged for that (yet?). It makes xraylarch dependency very heavy and not compatible with Python 3.8/3.9 in some cases (at least for NSLS-II deployments, we have to stick with 3.7). Please let me know.

Here are the corresponding feedstocks:
- https://github.com/nsls-ii-forge/xraylarch-feedstock/blob/master/recipe/meta.yaml
- https://github.com/nsls-ii-forge/analysis-feedstock/blob/de531d3075e6d016db2c11c06513293c0078e25a/recipe/meta.yaml#L113

**Comment by newville** [comment]
@mrakitin The xraylarch library does not require wxpython.  That is reflected in setup.py, and using `pip install xraylarch` will install the latest version and ensure that all required packages (not wxpython) are installled.  Of course, if you want to use the graphical applications, you need wxpython. There are a handful of other libraries that are required for some functionalities, but not required to use the library.  These are listed in `requirements-extra.txt`.

What Anaconda python does (or which channels to use with it) is sort of a different question.   Obviously, I have no control over the NSLS-II conda recipes you point to.   Your recipe for xraylarch package could remove wxpython (and wxutils and wxmplot).   

But I can say that I have experienced many challenges with conda and other libraries (tomopy, pyfai, dioptas, as well as wxpython).  Conda-forge seems like a reasonable source of these packages, but conda-forge is not without its own headaches.   Basically, I find `conda` and Anaconda Python to have gotten much more painful to deal with over the past couple of years. I've pretty much given up trying to maintain conda recipes or my own conda channel.    

It turns out that xraylarch (and, actually, all my packages including pyepics, which you may or may not be using) are pure python packages with external dynamic libraries included.  That makes them most easily (and most reliably) installed with pip, which allows using any python distribution, not limited to Anaconda Python.

In short, I recommend installing xraylarch with pip.  

That said, I do still use Anaconda Python and "conda constructor" to build the single-file installers.  This is also not-without-problems, but is still currently working ;).

Finally, slightly off-topic, but very important:  Your recipe for xraylarch is wrong in its removal of the feff binaries:  the binaries for Feff created, maintained, and distributed with xraylarch most definitely are built from source code with a liberal license permitting redistribution of source and binaries.  I don't know where you got the information in your recipe, but it is flat out wrong and must be changed.   Really, if you do not correct this, you should not use xraylarch at all.  Really, I am not kidding.  You are spreading misinformation about the license we use, and your really really have to stop doing that.

**Comment by mrakitin** [comment]
@newville, thanks for your reply. I'll answer below.

> @mrakitin The xraylarch library does not require wxpython. That is reflected in setup.py, and using `pip install xraylarch` will install the latest version and ensure that all required packages (not wxpython) are installled. Of course, if you want to use the graphical applications, you need wxpython. There are a handful of other libraries that are required for some functionalities, but not required to use the library. These are listed in `requirements-extra.txt`.

Thank you for the information. Our recipe was based on the state of the dependencies for v0.9.37, where [`matplotlib.use('WXAgg')` was used](https://github.com/xraypy/xraylarch/blob/a8c3fe3f3b723275edb0647332dd078bb2391775/lib/__init__.py#L13) without any conditions, causing the need for `wx`.

> What Anaconda python does (or which channels to use with it) is sort of a different question. Obviously, I have no control over the NSLS-II conda recipes you point to. Your recipe for xraylarch package could remove wxpython (and wxutils and wxmplot).

I'll update our recipe to exclude the `wx*` dependencies. 


> But I can say that I have experienced many challenges with conda and other libraries (tomopy, pyfai, dioptas, as well as wxpython). Conda-forge seems like a reasonable source of these packages, but conda-forge is not without its own headaches. Basically, I find `conda` and Anaconda Python to have gotten much more painful to deal with over the past couple of years. I've pretty much given up trying to maintain conda recipes or my own conda channel.

That's sad. Do you want to team up and create `xraylarch-feedstock` in the conda-forge org? https://github.com/conda-forge/xraylarch-feedstock is still available ;)

> It turns out that xraylarch (and, actually, all my packages including pyepics, which you may or may not be using) are pure python packages with external dynamic libraries included. That makes them most easily (and most reliably) installed with pip, which allows using any python distribution, not limited to Anaconda Python.

We do use `pyepics`, even more than `xraylarch`. But I disagree it's a pure Python package, as it depends on `libCA`.

> In short, I recommend installing xraylarch with pip.

Yes, that's what conda-build does inside of the recipe, making sure the packaged content is consistent with the declared dependencies + performs the basic tests.

> Finally, slightly off-topic, but very important: Your recipe for xraylarch is wrong in its removal of the feff binaries: the binaries for Feff created, maintained, and distributed with xraylarch most definitely are built from source code with a liberal license permitting redistribution of source and binaries. I don't know where you got the information in your recipe, but it is flat out wrong and must be changed. Really, if you do not correct this, you should not use xraylarch at all. Really, I am not kidding. You are spreading misinformation about the license we use, and your really really have to stop doing that.

That statement is against the BSD-2-Clause license for this repo:
https://github.com/xraypy/xraylarch/blob/558151bd2312fa583f89b816e29ea3af9e00169e/LICENSE#L12-L13
According to the text of the license, we do have a right to modify it and its binary form, if the conditions are met, which is true, i.e. the license file is a part of the generated artifacts (see https://github.com/nsls-ii-forge/xraylarch-feedstock/blob/eb990d7e9a979f48acdb6f4c6e5516ca25b3398f/recipe/meta.yaml#L65 and/or any file from https://anaconda.org/nsls2forge/xraylarch/files). The main concern here is the redistribution of the third-party binary. Could you please provide the information about its license and the script/instructions on how it was built? I do see the download links to the binaries in http://monalisa.phys.washington.edu/feff/Bin-Source-feff8Lite/Bin-Source.html, however, it's not clear what license is associated with them. The linked GitHub repo is hidden/not publicly available. So, we simply cannot take the responsibility of misuse if there is any hidden condition of the binaries which are included in the repo.

**Comment by mrakitin** [comment]
I'd like to invite my colleagues @cryos and @tacaswell to comment on the licensing aspect if you don't mind.

**Comment by cryos** [comment]
I share concerns about `feff8Lite`, it does not state what license is used, simply saying "FEFF8-Lite is a free version of the FEFF8 code, restricted to EXAFS calculations." I guess that means it is a proprietary license offered at no cost but only for EXAFS calculations. There does not appear to be an OSI-approved license here, simply an offer to use the binary at no cost for a narrow use case. I am not familiar with liberal license, but most of us would like to see an OSI-approved license, it does not seem that permissive to me unless there is a better source of licensing information available.

**Comment by newville** [comment]
On Mon, Jan 11, 2021 at 11:04 PM Maksim Rakitin <notifications@github.com>
wrote:

> @newville <https://github.com/newville>, thanks for your reply. I'll
> answer below.
>
> @mrakitin <https://github.com/mrakitin> The xraylarch library does not
> require wxpython. That is reflected in setup.py, and using pip install
> xraylarch will install the latest version and ensure that all required
> packages (not wxpython) are installled. Of course, if you want to use the
> graphical applications, you need wxpython. There are a handful of other
> libraries that are required for some functionalities, but not required to
> use the library. These are listed in requirements-extra.txt.
>
> Thank you for the information. Our recipe was based on the state of the
> dependencies for v0.9.37, where matplotlib.use('WXAgg') was used
> <https://github.com/xraypy/xraylarch/blob/a8c3fe3f3b723275edb0647332dd078bb2391775/lib/__init__.py#L13>
> without any conditions, causing the need for wx.
>
> What Anaconda python does (or which channels to use with it) is sort of a
> different question. Obviously, I have no control over the NSLS-II conda
> recipes you point to. Your recipe for xraylarch package could remove
> wxpython (and wxutils and wxmplot).
>
> I'll update our recipe to exclude the wx* dependencies.
>

Yeah, we've made some progress since then.  ;)

But I can say that I have experienced many challenges with conda and other
> libraries (tomopy, pyfai, dioptas, as well as wxpython). Conda-forge seems
> like a reasonable source of these packages, but conda-forge is not without
> its own headaches. Basically, I find conda and Anaconda Python to have
> gotten much more painful to deal with over the past couple of years. I've
> pretty much given up trying to maintain conda recipes or my own conda
> channel.
>
> That's sad. Do you want to team up and create xraylarch-feedstock in the
> conda-forge org? https://github.com/conda-forge/xraylarch-feedstock is
> still available ;)
>

I don't have a very strong opinion one way or the other.  Conda recipes and
conda-forge are kind of like another layer of stuff to do.  My view is that
we definitely need "pip install" to work.  Beyond that, I don't have a
strong opinion.

It turns out that xraylarch (and, actually, all my packages including
> pyepics, which you may or may not be using) are pure python packages with
> external dynamic libraries included. That makes them most easily (and most
> reliably) installed with pip, which allows using any python distribution,
> not limited to Anaconda Python.
>
> We do use pyepics, even more than xraylarch. But I disagree it's a pure
> Python package, as it depends on libCA.
>

Well, xraylarch and pyepics *are* pure Python in the sense that they
contain no code that needs to be compiled at install-time for the specific
OS and version of Python.  There is no `setuptools.Extension` code.   They
do both interact with dynamic libraries, but those libraries are
independent of Python and are used exclusively through the `ctypes`
module.  This means that these libraries can be compiled for a particular
OS (and glibc generation or equivalent), but not for a particular version
of Python.  These dynamic libraries can then be treated as "package data"
and be distributed without modification and loaded at runtime with
`ctypes`.   Using `ctypes` makes the code be pure python.  This is what is
done for both pyepics and xraylarch.   To be sure, making reliably
redistributable binary libs can be challenging (especially for Linux! MacOS
has much less tolerance for such trouble and this variant of "DLL HELL" is
very easy to work around on Windows).  As it turns out, installing the
supplied dynamic libraries as package data also effectively means they do
not cause "DLL HELL", as they will not be placed in paths where they could
be accidentally loaded by non-Python code.

In practice, that means that "pip install" or "python setup.py install"
will install working versions of xraylarch (and pyepics) on machines
without working compilers.  Just to be clear, the conda-forge recipe for
pyepics will install epics core libraries and a perl interpreter(!) as
so-called dependencies.  Of course, those are not actually dependencies -
the recipe is simply wrong.   "pip install pyepics" installs a working
interface for pyepics on python environments without *any other* epics
installation and without installing any other python dependencies (numpy is
highly recommended but not required, and pyparsing is required by one
submodule).  It certainly does not install other Epics binaries or a Perl
interpreter.


In short, I recommend installing xraylarch with pip.
>
> Yes, that's what conda-build does inside of the recipe, making sure the
> packaged content is consistent with the declared dependencies + performs
> the basic tests.
>
> Finally, slightly off-topic, but very important: Your recipe for xraylarch
> is wrong in its removal of the feff binaries: the binaries for Feff
> created, maintained, and distributed with xraylarch most definitely are
> built from source code with a liberal license permitting redistribution of
> source and binaries. I don't know where you got the information in your
> recipe, but it is flat out wrong and must be changed. Really, if you do not
> correct this, you should not use xraylarch at all. Really, I am not
> kidding. You are spreading misinformation about the license we use, and
> your really really have to stop doing that.
>
> That statement is against the BSD-2-Clause license for this repo:
>
> https://github.com/xraypy/xraylarch/blob/558151bd2312fa583f89b816e29ea3af9e00169e/LICENSE#L12-L13
> According to the text of the license, we do have a right to modify it and
> its binary form, if the conditions are met, which is true, i.e. the license
> file is a part of the generated artifacts (see
> https://github.com/nsls-ii-forge/xraylarch-feedstock/blob/eb990d7e9a979f48acdb6f4c6e5516ca25b3398f/recipe/meta.yaml#L65
> and/or any file from https://anaconda.org/nsls2forge/xraylarch/files).
>

One of the (very few) licensing conditions with BSD/MIT is that the
licensing and redistribution information be preserved.  The comment in your
conda recipe states that you do not have a license to redistribute the Feff
binaries included with xraylarch.  This is not true: you are permitted to
redistribute all of it in source or binary form. Indeed, it is your right
to not use or distribute the Feff binaries.  But, you cannot say that you
are not permitted to do so.  That is a misrepresentation of the license.

The main concern here is the redistribution of the third-party binary.
> Could you please provide the information about its license and the
> script/instructions on how it was built? I do see the download links to the
> binaries in
> http://monalisa.phys.washington.edu/feff/Bin-Source-feff8Lite/Bin-Source.html,
> however, it's not clear what license is associated with them. The linked
> GitHub repo is hidden/not publicly available. So, we simply cannot take the
> responsibility of misuse if there is any hidden condition of the binaries
> which are included in the repo.
>

The licenses from and related to the Feff project can be confusing.  The
latest development code as distributed from U Washington would indeed not
be permissible for us to distribute - that code and those binaries can be
used but cannot be transferred.  The source is provided to users, but it
does not use an open-source compatible license.  We do not distribute
binaries built from that code.

But we do have BSD-2-like versions of Feff6 and Feff8 (typically with an
added 'l') and have had these for a very long time.  These are used to
build the binaries that we distribute.  This code for all of this is
currently at https://github.com/xraypy/feff85exafs (a companion project to
xraylarch and many people use these Feff versions without xraylarch), with
license files.  As it turns out Bruce Ravel (who you may know) and I spent
a lot of time and effort to get these codes to be licensed so that we (and
you!) could redistribute them without violating the U Washington license or
copyrights of Rehr, Ankudinov, Kas,  et al for their latest development
version of Feff.  As it happens, both Bruce and I were at U Washington
where and when these codes were developed, we're on friendly terms with all
of the PIs and developers. This effort to get an open-source "lite" version
of Feff actually began more than 20 years ago, and Feff6l has been licensed
under a BSD/MIT-like license since 2002 or so.  Feff8l (also known as
Feff85exafs of Feff85lite) has been available with such a license for about
10 years.  This is described partly at
https://xraypy.github.io/xraylarch/installation.html#acknowledgements

In short, we most certainly do have the right to redistribute this code and
these binaries, and so do you.  Your recipe misrepresents the actual
situation.   Again, I don't care if you remove the feff binaries, but I do
very much care that you state that you are not permitted to do so.

--Matt

**Comment by cryos** [comment]
> But we do have BSD-2-like versions of Feff6 and Feff8 (typically with an
> added 'l') and have had these for a very long time.  These are used to
> build the binaries that we distribute.  This code for all of this is
> currently at https://github.com/xraypy/feff85exafs (a companion project to
> xraylarch and many people use these Feff versions without xraylarch), with
> license files.  As it turns out Bruce Ravel (who you may know) and I spent
> a lot of time and effort to get these codes to be licensed so that we (and
> you!) could redistribute them without violating the U Washington license or
> copyrights of Rehr, Ankudinov, Kas,  et al for their latest development
> version of Feff.  As it happens, both Bruce and I were at U Washington
> where and when these codes were developed, we're on friendly terms with all
> of the PIs and developers. This effort to get an open-source "lite" version
> of Feff actually began more than 20 years ago, and Feff6l has been licensed
> under a BSD/MIT-like license since 2002 or so.  Feff8l (also known as
> Feff85exafs of Feff85lite) has been available with such a license for about
> 10 years.  This is described partly at
> https://xraypy.github.io/xraylarch/installation.html#acknowledgements

I didn't see this, but the repo you link to and the license are indeed OSI-approved. Thank you for taking the time to clear this up, I think that the license is 2-clause BSD according to my reading (not just BSD-like). Thanks to you and Bruce for your efforts to apply a license with full rights to modify, redistribute and share.

**Comment by mrakitin** [comment]
Thank you for the very detailed explanation, @newville. I do see https://github.com/xraypy/feff85exafs/blob/master/LICENSE_Feff6L.txt (for v6 though). I happened to look at http://monalisa.phys.washington.edu/feff/Bin-Source-feff8Lite/Source/feff85L.f (from http://monalisa.phys.washington.edu/feff/Bin-Source-feff8Lite/Bin-Source.html), and it has the same license (for 8.5L) in the header. As @cryos pointed, the license is indeed BSD 2-Clause. I think we can remove our patches for the feff binaries. We will discuss it internally.

Thank you.
