### ISSUE TITLE
[Group] Link or store sub-groups (e.g. energy reference)

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#329]
This is a new feature discussed with @newville : have the possibility to link or store (= copy) one or more sub-groups to a given group. For example, a typical use case is having the spectrum of a metallic foil measured for energy calibration.

The `xas_viewer` GUI should be able to have a ckeckbox or menu entry to show/hide such the sub-groups, for the selected groups. This will permit working on the subgroups when required and avoid polluting the list of groups otherwise.

**Comment by newville** [comment]
I think this works much better with 0.9.60 - each group does have an "energy_reference" attribute -- the *name* of another group (default is its own name).  When energy aligning/shifting spectra, there is an option to select all groups that share a reference, so that they can all be calibrated together.
