### ISSUE TITLE
[xas_viewer/CIF files] handle half/partial occupation

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#343]
@newville a user sent me a [CIF file for PtFe/Ni alloy](https://github.com/xraypy/xraylarch/files/7903049/1522951.cif.zip) taken from  http://crystallography.net database, which has half occupation and is not running.

Furthermore, I propose to make the "CIF text" tab editable.

**Comment by newville** [comment]
@maurov Partial occupancy should not fail - and should use random selection to fill atomc sites.  I have seen other CIF files from COD work.   So, I'm not sure why that one is failing.... will investigate.

**Comment by newville** [comment]
@maurov but also: editable CIF file is a good idea!

**Comment by maurov** [comment]
@newville thanks for looking into this. I have updated the initial text of the issue because what I wrote was partially wrong, sorry for that!

**Comment by maurov** [comment]
@newville  I confirm that the problem comes from the CIF file, not how partial occupation is handled in Larch. Here [a couple of FeNiPt CIF files from ICSD](https://github.com/xraypy/xraylarch/files/7907002/FeNiPt_ICSD_cifs.zip) we could use for comparison/testing.

**Comment by newville** [comment]
@maurov A partial update:  Fractional occupancy now works.  I would have sworn it did this summer, but it must have been that either it was not working for the absorbing atom to be in a partially occupied site, or pymatgen results changed (and must have improved) or some combination. 

But the two FeNiPt files you post from ICSD still do not properly work as the journal citation and author information is not being properly handled.  Those CIFs use a completely different set of tags with "citation" instead of "journal".  I don't see any files from https://crystallography.net/ with those tags.  Not sure how (or whether!) to deal with that.

**Comment by newville** [comment]
@maurov  OK, an update to the update:  the CIF files from ICSD are parsed better (especially for Journal/Author info) and partial occupancy works better.

**Comment by maurov** [comment]
@newville thanks for working on this. It seems fine to me. I just propose to let the CIF text panel writable.
