### ISSUE TITLE
[xas_viewer] data point selector as in Athena?

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#353]
@newville many users (including myself) do not like the behavior of the data point selector in xas_viewer, that is, first click on the plot and then click on the pin button in the GUI to get the value. The behavior in Athena seems much more intuitive and appreciated, that is:

- click on the pin button
- a cross-line shows in the plot to let choose the data point
- once clicked this point is taken into the GUI

Do you think this is worth to replicate and who much easy is it to implement?

Thanks for your comments

**Comment by newville** [comment]
@maurov I think I have this working.  It's slightly more complicated, but I think it will be better for all.  

Here is a basic rundown:
Every time you click on the plot, the cursor (x, y) and time are recorded.  Previously, clicking on the Pin Icon took the most recent value.

Now, it looks if there is a recent (5 seconds ago) cursor position and initializes with that.  Then, it starts a timer.  If the user clicks on the plot after that (and so, if new cursor values come in), that value will be used.  It waits 3 seconds before returning, taking the most recent value so that if you click many times, the last will be used.  After 3 seconds, as soon as the user clicks, that value will be used.   There is a timeout for the Timer of 15 seconds -- it will stop looking for events after that and may return the most recent value.

All of those time values could be made into Preferences. So far we don't really have any user-settable preferences, but we could.....

**Comment by maurov** [comment]
@newville thanks for implementing this. I have tested it and it behaves as expected, great!

And yes, I think it is a good idea to have user-settable preferences in xas_viewer. I will open a dedicated issue with lower priority for that.
