### ISSUE TITLE
"Plot Selected Groups" not working after import Larch session using "Read Larch Session"

### ISSUE THREAD

**Issue by rarivera10** [xraypy/xraylarch#526]
After I import a previously saved Larch session using "Read Larch Session", if I try to plot multiple groups, then nothing plots and I receive an error in the terminal saying:

> Traceback (most recent call last):
>   File "C:\Users\rariv\xraylarch\lib\site-packages\larch\wxxas\xasnorm_panel.py", line 586, in onPlotSel
>     trace = {'xdata': dgroup.xplot,
> AttributeError: 'Group' object has no attribute 'xplot'

This did not happen before updating to 0.9.80 on Windows.

If I open new data files from CSV and I plot multiple groups, then things work normally however.

**Comment by newville** [comment]
@rarivera10 Oh, sorry for the trouble.   Can you send a session file that shows this?

**Comment by rarivera10** [comment]
Yes! Github doesn't let me attach a .larix file so I sent the file in an email to newville@cars.uchicago.edu.

**Comment by newville** [comment]
@rarivera10 

I believe this is fixed in the "development version", which you should be able to install with
 ```
    python -m pip install https://millenia.cars.aps.anl.gov/xraylarch/downloads/xraylarch-latest-py3-none-any.whl
```

On Windows: Open a command terminal (with “cmd” in the Start Menu’s search box).  This should put you in a folder like
      C:\Users\yourname
There should be a folder called `xraylarch` there.  If not, check the properties of the Desktop icons for where xraylarch is installed.  Once that is found, you can then you can type:

```
     xraylarch\python -pip install https://millenia.cars.aps.anl.gov/xraylarch/downloads/xraylarch-latest-py3-none-any.whl
```

**Comment by rarivera10** [comment]
Downloaded and I receive a new error now:

> Traceback (most recent call last):
>   File "C:\Users\rariv\xraylarch\lib\site-packages\larch\wxxas\xasnorm_panel.py", line 586, in onPlotSel
>     'ydata': getattr(dgroup, yarray_name) + ix*voff,
> AttributeError: 'Group' object has no attribute 'norm_mback'

When normalization is set to mback on a group and I try to plot multiple groups, then I receive this error. However, plotting multiple groups with polynomial normalization works great. Mback works fine when I plot current group, I only see the problem when plotting multiple groups and one of them uses mback for normalization.

Thankfully, I only need polynomial normalization but figured I'd report the mback error as well since I stumbled upon it.

Thank you for your help!! I have enjoyed using Larix and am excited for the improvements you continue to make to the software.

**Comment by newville** [comment]
@rarivera10 Thanks for the report and sorry for that.  That's clear enough that I'll look into (maybe in a couple of days).

**Comment by maurov** [comment]
@newville this bug with 'norm_mback' was already reported in #511

**Comment by newville** [comment]
@maurov Thanks, that's helpful, and I agree these must be related...  hope to fix soon!

**Comment by newville** [comment]
@rarivera10 @maurov I *think* this is fixed in the master branch.  I fixed the code to check for the arrays from mback, and run that if needed (and be more aggressive about running mback n general), and I wasn't able to make it happen.  But, I'm not certain I was trying every possible approach.   If you are up for trying as with

     https://xraypy.github.io/xraylarch/installation.html#installing-the-development-version

let me know if this is still happening for you.

**Comment by rarivera10** [comment]
Everything appears to be working well for me now. Will update if I run into the issue again. Thanks for the fix!
