### ISSUE TITLE
Error Loading Pre-edge Fit Result

### ISSUE THREAD

**Issue by LJRH** [xraypy/xraylarch#540]
Version: Larix Larch 0.9.81 (RHEL 7.9)
Module: larix / pre_edge()
Dataset: HERFD-XANES Fe K-edge

Description: Clicking the 'Load Fit Result' to load a previously generated model does not work. Error given is:

![image](https://github.com/user-attachments/assets/e39d71ce-1773-4d9e-8f1a-68cb27467f24)

```
Traceback (most recent call last):
  File "/dls/science/users/<me>/.conda/envs/xraylarch/lib/python3.12/site-packages/larch/wxxas/prepeak_panel.py", line 1341, in onLoadFitResult
    rfile = FileOpen(self, "Load Saved Pre-edge Model",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls/science/users/<me>/.conda/envs/xraylarch/lib/python3.12/site-packages/larch/wxlib/__init__.py", line 72, in FileOpen
    result = wxu.FileOpen(parent, message, **kws)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls/science/users/<me>/.conda/envs/xraylarch/lib/python3.12/site-packages/wxutils/dialogs.py", line 46, in FileOpen
    dlg = wx.FileDialog(parent, message=message, wildcard=wildcard,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FileDialog(): argument 'defaultFile' has unexpected type 'NoneType'
```

I tried following the error back through the code, but it wasn't entirely obvious where the issue was. It would be good to be able to load models from datasets from older versions of larix/xasviewer.

Best Wishes,
Luke

**Comment by LJRH** [comment]
Downgraded to version 0.9.80, where the 'Load Fit Result' is still working.

**Comment by newville** [comment]
@LJRH @maurov I think I have this fixed in the master branch (and also #541).  I can save and reload Session files (on macOS). I'll try on Linux and Windows later today.

Also: sorry for the trouble.  I've been trying to "normalize" my codes to be more consistent and have fewer copied bit of code, and also to better use `pathlib.Path`.... and this has introduced some bugs -- and GUIs are hard to test (and Larch does not have nearly enough testing anyway).  

FWIW, I think we should aim for next version (and switch to date-based version tags) around Dec 1, merging #536, making sure #532 and related issues on load/save are fixed, and doing a lot of testing of the loading/saving data steps.

**Comment by maurov** [comment]
@newville thanks for fixing this! I agree to move to date-based version and release `2024.12.0` soon. I am tagging those issues fixed for the next release.

@LJRH could you check that the latest master version fixes this issue and give a feedback? If it works, please, close the issue.

**Comment by newville** [comment]
@maurov Thanks! I expect to do a lot of Larix testing this weekend, be ready for a "release candidate" by Monday (including the Larixite dependency), and maybe aim to push out 2024.12.0 by the end of next week.

**Comment by LJRH** [comment]
@maurov @newville 

Doing an upgrade using standard method (below), **did not** fix the issue.
`pip install --upgrade xraylarch`

Cloning and compiling the new release candidate _Larch 2024.12.0rc1_ using the method described [in the documentation](http://xraypy.github.io/xraylarch/installation.html#larch-for-developers-source-installation) **did** solve the problem. I can now load models using the _Load Fit Result_ button.

Thanks for your support!

**Comment by newville** [comment]
@LJRH Thanks, and glad to hear it is working!
