### ISSUE TITLE
surprising show() behavior

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#98]
After doing a feffit at the larch command line, this works:
```
show(fit.datasets[0])
```
but this, without the parens:
```
larch> show fit.datasets[0]
file <stdin>, line 0
SyntaxError: invalid syntax
show fit.datasets[0]

    show fit.datasets[0]
```

**Comment by newville** [comment]
huh, might be related to #99?

**Comment by newville** [comment]
Actually, I think this is because the code to convert `command string` to to `command(string)` only works if `string` is a **symbol**, not an expression.  So      `show 1+2` does not work, though `show(1+2)` does (hint: 3).    I don't remember exactly why that is the case, but I think that there was a reason... I'll try to remember this.   But, basically the `command string` thing is very weak.

Still don't know if this is related to #99....

**Comment by bruceravel** [comment]
I believe this is resolved.
